# Generated by Django 5.0.1 on 2024-01-17 17:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="email",
            field=models.EmailField(default="", max_length=254),
        ),
        migrations.AlterField(
            model_name="contact",
            name="name",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="contact",
            name="subject",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="post",
            name="description",
            field=models.TextField(default="", max_length=1000),
        ),
        migrations.AlterField(
            model_name="post",
            name="title",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="post",
            name="url",
            field=models.URLField(default=""),
        ),
        migrations.AlterField(
            model_name="post",
            name="votes",
            field=models.IntegerField(default=0),
        ),
    ]
